// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU-SuoNHRJUHGWH7PHPyx5qEouSSDyi-4',
    appId: '1:789022701717:web:8dac71ed5fb13620a0c39c',
    messagingSenderId: '789022701717',
    projectId: 'schoolprojectjan',
    authDomain: 'schoolprojectjan.firebaseapp.com',
    storageBucket: 'schoolprojectjan.firebasestorage.app',
    measurementId: 'G-9VS9XMC1QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrMjI25o0eB-ZMUXBCi4vazard75Eg3HE',
    appId: '1:789022701717:android:a3a4785eabad3571a0c39c',
    messagingSenderId: '789022701717',
    projectId: 'schoolprojectjan',
    storageBucket: 'schoolprojectjan.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU-SuoNHRJUHGWH7PHPyx5qEouSSDyi-4',
    appId: '1:789022701717:web:92db4624dc12b262a0c39c',
    messagingSenderId: '789022701717',
    projectId: 'schoolprojectjan',
    authDomain: 'schoolprojectjan.firebaseapp.com',
    storageBucket: 'schoolprojectjan.firebasestorage.app',
    measurementId: 'G-D5JXV6CZ5S',
  );
}
